buses: buses.yaml
enum_types: enums.yaml
struct_types: structs.yaml
nodes:
  motor_driver: motor_driver.yaml
  input_board: input_board.yaml
  guidance_board_front: guidance_board.yaml
  guidance_board_back : guidance_board.yaml
  levitation_board_front: levitation_board.yaml
  levitation_board_middle: levitation_board.yaml
  levitation_board_back: levitation_board.yaml

